import {
  ActivityIcon,
  AirplaneIcon,
  AlarmIcon,
  ArchiveIcon,
  BabyIcon,
  BackpackIcon,
  BarbelIcon,
  BaseballIcon,
  BedIcon,
  BellIcon,
  BirdIcon,
  BookIcon,
  CameraIcon,
  CarIcon,
  CloudIcon,
  CodeIcon,
  CoinIcon,
  DollarIcon,
  GearIcon,
  HandWaving,
  InfinityIcon,
  MoneyIcon,
  UserIcon,
  Wheelchair,
} from "../../assets";

export const CategoryColorKey = [
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "pink",
  "rose",
];

export const CategoryColorHueKey = ["100", "200", "300", "400"];

export const CategoryColor = CategoryColorHueKey.map((hueKey) =>
  CategoryColorKey.map((colorKey) => `bg-${colorKey}-${hueKey}`),
).flat();

export const CategoryIcon = {
  people: ({ size }: { size: number }) => <UserIcon size={size} />,
  money: ({ size }: { size: number }) => <MoneyIcon size={size} />,
  coin: ({ size }: { size: number }) => <CoinIcon size={size} />,
  airplane: ({ size }: { size: number }) => <AirplaneIcon size={size} />,
  archive: ({ size }: { size: number }) => <ArchiveIcon size={size} />,
  backpack: ({ size }: { size: number }) => <BackpackIcon size={size} />,
  baby: ({ size }: { size: number }) => <BabyIcon size={size} />,
  barbell: ({ size }: { size: number }) => <BarbelIcon size={size} />,
  baseball: ({ size }: { size: number }) => <BaseballIcon size={size} />,
  bed: ({ size }: { size: number }) => <BedIcon size={size} />,
  book: ({ size }: { size: number }) => <BookIcon size={size} />,
  car: ({ size }: { size: number }) => <CarIcon size={size} />,
  dollar: ({ size }: { size: number }) => <DollarIcon size={size} />,
  activity: ({ size }: { size: number }) => <ActivityIcon size={size} />,
  bird: ({ size }: { size: number }) => <BirdIcon size={size} />,
  alarm: ({ size }: { size: number }) => <AlarmIcon size={size} />,
  code: ({ size }: { size: number }) => <CodeIcon size={size} />,
  bell: ({ size }: { size: number }) => <BellIcon size={size} />,
  infinity: ({ size }: { size: number }) => <InfinityIcon size={size} />,
  handWaving: ({ size }: { size: number }) => <HandWaving size={size} />,
  wheelchair: ({ size }: { size: number }) => <Wheelchair size={size} />,
  gear: ({ size }: { size: number }) => <GearIcon size={size} />,
  cloud: ({ size }: { size: number }) => <CloudIcon size={size} />,
  camera: ({ size }: { size: number }) => <CameraIcon size={size} />,
};
export const CategoryIconKey = Object.keys(CategoryIcon);
